In [1]:
1 + 1

2

In [2]:
import pandas as pd
pd.__version__

'3.0.5'

In [3]:
import pandas as pd

In [4]:
x = 999

In [5]:
x * 3

2997

In [6]:
print("첫줄")
print("둘째줄")
x

첫줄
둘째줄

999

In [7]:
import pandas as pd
df = pd.read_csv("data/sales.csv")
df.head()

           날짜  지역   제품  수량      단가
0  2025-01-01  부산  모니터  12  260000
1  2025-01-02  대구  모니터  17  345000
2  2025-01-02  인천  마우스  15   29000
3  2025-01-07  인천  키보드  16   26000
4  2025-01-08  부산  모니터  14  372000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      200 non-null    str
 1   지역      200 non-null    str
 2   제품      200 non-null    str
 3   수량      200 non-null    int64
 4   단가      200 non-null    int64
dtypes: int64(2), str(3)
memory usage: 7.9 KB

In [9]:
df.describe()

               수량            단가
count  200.000000  2.000000e+02
mean    10.400000  3.551600e+05
std      5.660406  4.604570e+05
min      1.000000  1.000000e+04
25%      5.000000  2.600000e+04
50%     10.000000  1.555000e+05
75%     16.000000  3.742500e+05
max     20.000000  1.485000e+06

In [10]:
import pandas as pd
df = pd.read_csv("data/sales.csv")

# 전체 매출 총합
df["매출"] = df["수량"] * df["단가"]
전체합 = df["매출"].sum()
print("전체 매출:", 전체합)

# 지역별로 나눠서 더한 것의 합
지역별합 = df.groupby("지역")["매출"].sum().sum()
print("지역별 합의 합:", 지역별합)

전체 매출: 739353000
지역별 합의 합: 739353000